steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: cacheLatest
    entrypoint: 'bash'
    args:
     - '-c'
     - |
        ( docker pull gcr.io/zcash-web/bb-worker-debian8:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-debian9:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-debian10:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-ubuntu1604:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-ubuntu1804:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-ubuntu1904:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-centos:latest || exit 0 );
        ( docker pull gcr.io/zcash-web/bb-worker-arch:latest || exit 0 );

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.debian8', '--tag=gcr.io/zcash-web/bb-worker-debian8', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-debian8:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.debian9', '--tag=gcr.io/zcash-web/bb-worker-debian9', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-debian9:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.debian10', '--tag=gcr.io/zcash-web/bb-worker-debian10', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-debian10:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.ubuntu1604', '--tag=gcr.io/zcash-web/bb-worker-ubuntu1604', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-ubuntu1604:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.ubuntu1804', '--tag=gcr.io/zcash-web/bb-worker-ubuntu1804', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-ubuntu1804:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.ubuntu1904', '--tag=gcr.io/zcash-web/bb-worker-ubuntu1904', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-ubuntu1904:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.centos', '--tag=gcr.io/zcash-web/bb-worker-centos', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-centos:latest']
    waitFor: ['cacheLatest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.arch', '--tag=gcr.io/zcash-web/bb-worker-arch', 'bb-worker/', '--cache-from', 'gcr.io/zcash-web/bb-worker-arch:latest']
    waitFor: ['cacheLatest']
images:
  - gcr.io/zcash-web/bb-worker-debian8
  - gcr.io/zcash-web/bb-worker-debian9
  - gcr.io/zcash-web/bb-worker-debian10
  - gcr.io/zcash-web/bb-worker-ubuntu1604
  - gcr.io/zcash-web/bb-worker-ubuntu1804
  - gcr.io/zcash-web/bb-worker-ubuntu1904
  - gcr.io/zcash-web/bb-worker-centos
  - gcr.io/zcash-web/bb-worker-arch
timeout: 1200s
