ARG FROMBASEOS
FROM gcr.io/zcash-web/bb-worker-$FROMBASEOS-build-python:3.7
ARG DEBIAN_FRONTEND=noninteractive

ADD apt-package-list.txt /tmp/apt-package-list.txt
RUN apt-get update \
    && apt-get install -y $(tr "\n" " " < /tmp/apt-package-list.txt) \
    && apt-get install -y dumb-init

# Buildbot user
ARG BUILDBOT_USER=zcbbworker
ARG BUILDBOT_UID=2001
RUN useradd --home-dir /home/$BUILDBOT_USER \
            --shell /bin/bash \
            --create-home \
            --uid $BUILDBOT_UID\
            $BUILDBOT_USER

USER $BUILDBOT_USER
WORKDIR /home/$BUILDBOT_USER

ADD requirements.txt requirements.txt
RUN python -m venv venv \
    && . venv/bin/activate \
    && python -m pip install -r requirements.txt

# Buildbot worker
ARG BASEOS
ENV BUILDBOT_WORKER_NAME=$BASEOS-docker
ENV BUILDBOT_WORKER_PASS=thisgetssetwhenpodisstarted
ENV BUILDBOT_MASTER_HOST=dev-ci.z.cash
ENV BUILDBOT_MASTER_PORT=9899

WORKDIR /home/$BUILDBOT_USER
RUN venv/bin/buildbot-worker create-worker $BUILDBOT_WORKER_NAME \
      $BUILDBOT_MASTER_HOST:$BUILDBOT_MASTER_PORT \
      $BUILDBOT_WORKER_NAME $BUILDBOT_WORKER_PASS \
    && echo "OS: $BASEOS" > $BUILDBOT_WORKER_NAME/info/host
ADD buildbot.tac $BUILDBOT_WORKER_NAME/buildbot.tac

WORKDIR /home/$BUILDBOT_USER/$BUILDBOT_WORKER_NAME
CMD ["/usr/bin/dumb-init", "../venv/bin/twistd", "--pidfile=", "-ny", "buildbot.tac"]
